#ifndef YACS_CONFIG_VERSION_H
#define YACS_CONFIG_VERSION_H

#define _STR(arg) #arg
#define _XSTR(arg) _STR(arg)

#define YACS_VERSION_MAJOR 0
#define YACS_VERSION_MINOR 1
#define YACS_VERSION_PATCH 0

#define YACS_VERSION        \
  _XSTR(YACS_VERSION_MAJOR) \
  "." _XSTR(YACS_VERSION_MINOR) "." _XSTR(YACS_VERSION_PATCH)

#endif